### PR TITLE
Removing bad comment from README

### PR DESCRIPTION
**Pull request by vcampitelli**
Removes a bad comment from the `README` file

### CODE REVIEW

**Comment by mooreds** [comment]
Isn't this still true, @vcampitelli ?

**Comment by vcampitelli** [comment]
It is true but it's not on a comment so it's showing on the actual README file. I thought of actually commenting it out but that already happens on https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/README.md?plain=1#L36.

So we can either remove it (like I did) or comment it.

**Comment by mooreds** [comment]
I guess I don't understand. This is a valid part of the readme (telling people who edit it to use backticks). What am I missing?

**Comment by vcampitelli** [comment]
Okay then, if that is the goal. I just found it strange and thought that this happened due to a bad copy/paste, as the other message that says the [same thing here](https://github.com/FusionAuth/fusionauth-react-sdk/blob/main/README.md?plain=1#L36) is commented out. Closing this.

**Pull request closed without merging**
