### PR TITLE
fix: better handling of bad user cookies

### PR DESCRIPTION
**Pull request by osbornm**
## What is this PR and why do we need it?

Right now, if the token-exchange endpoint does not return a user property a cookie is set with the value `undefined`. The problem is that on the next full page refresh this value is parsed as JSON and the error is not caught and the provider crashes. This PR adds some guards to both setting bad tokens and catching those page crashing errors. 

#### Pre-Merge Checklist (if applicable)

-   [ ] Unit and Feature tests have been added/updated for logic changes, or there is a justifiable reason for not doing so.

I will add these if this is the direction the team wants to go.

### CODE REVIEW

**Comment by robotdan** [comment]
Thanks for the PR @osbornm !!

**Comment by osbornm** [comment]
@robotdan do you want to move forward with this? if so I can add the tests?

**Comment by robotdan** [comment]
@bhalsey @mooreds or @sam-woodridge will be reviewing the PR.

**Comment by bhalsey** [comment]
Thanks for the PR @osbornm .  Yes, please add a test for an undefined user.
Thanks!

**Comment by osbornm** [comment]
@bhalsey done

**Comment by bhalsey** [comment]
Great, thank you.  Can you merge main and bump the version patch number?  (to `0.23.2`).  Then this will be ready to merge.

**Comment by osbornm** [comment]
@bhalsey since the version was already .2 I assumed you wanted it bumped to .3

**Review by bhalsey — APPROVED** [review]
Right on the version number!  Thanks for your contribution.

**Comment by osbornm** [comment]
@bhalsey can you cut a release please :)

**Comment by bhalsey** [comment]
Done!

**Pull request merged**
